name: Deploy to AWS Lightsail

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker images
      run: |
        docker build -t javohirgo/car-wash-system-gateway ./GATEWAY
        docker build -t javohirgo/car-wash-system-booking ./BOOKING
        docker build -t javohirgo/car-wash-system-auth ./AUTH

    - name: Push Docker images to Docker Hub
      run: |
        docker push javohirgo/car-wash-system-gateway:latest
        docker push javohirgo/car-wash-system-booking:latest
        docker push javohirgo/car-wash-system-auth:latest

    - name: Execute Commands on Remote Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USER }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        port: "22"
        script: |
          cd /car-wash-system
          docker compose down
          docker compose pull
          docker compose up -d
        timeout: 30s
        command_timeout: 10m
